local name, addon = ...;

addon.talents = {
    ["Warrior"] = {
        ["Arms"] = {
            "Deflection (Rank 1)",
            "Deflection (Rank 2)",
            "Improved Rend (Rank 1)",
            "Improved Rend (Rank 2)",
            "Improved Rend (Rank 3)",
            "Improved Charge (Rank 1)",
            "Improved Charge (Rank 2)",
            "Tactical Mastery (Rank 1)",
            "Tactical Mastery (Rank 2)",
            "Tactical Mastery (Rank 3)",
            "Improved Overpower (Rank 1)",
            "Improved Overpower (Rank 2)",
            "Deep Wounds (Rank 1)",
            "Deep Wounds (Rank 2)",
            "Deep Wounds (Rank 3)",
            "Two-Handed Weapon Specialization (Rank 1)",
            "Two-Handed Weapon Specialization (Rank 2)",
            "Two-Handed Weapon Specialization (Rank 3)",
            "Two-Handed Weapon Specialization (Rank 4)",
            "Two-Handed Weapon Specialization (Rank 5)",
            "Sweeeping Strikes",
            "Axe Specialization (Rank 1)",
            "Axe Specialization (Rank 2)",
            "Axe Specialization (Rank 3)",
            "Axe Specialization (Rank 4)",
            "Axe Specialization (Rank 5)",
            "Tactical Mastery (Rank 4)",
            "Tactical Mastery (Rank 5)",
            "Anger Management",
            "Deflection (Rank 3)",
            "Mortal Strike",
            "Cruelty (Rank 1)",
            "Cruelty (Rank 2)",
            "Cruelty (Rank 3)",
            "Cruelty (Rank 4)",
            "Cruelty (Rank 5)",
            "Unbridled Wrath (Rank 1)",
            "Unbridled Wrath (Rank 2)",
            "Unbridled Wrath (Rank 3)",
            "Unbridled Wrath (Rank 4)",
            "Unbridled Wrath (Rank 5)",
            "Improved Battle Shout (Rank 1)",
            "Improved Battle Shout (Rank 2)",
            "Improved Battle Shout (Rank 3)",
            "Improved Battle Shout (Rank 4)",
            "Improved Battle Shout (Rank 5)",
            "Enrage (Rank 1)",
            "Enrage (Rank 2)",
            "Enrage (Rank 3)",
            "Enrage (Rank 4)",
            "Enrage (Rank 5)"
        }
    },
    ["Rogue"] = {
        ["Swords"] = {
            "Improved Sinister Strike (Rank 1)",
            "Improved Sinister Strike (Rank 2)",
            "Improved Gouge (Rank 1)",
            "Improved Gouge (Rank 2)",
            "Improved Gouge (Rank 3)",
            "Precision (Rank 1)",
            "Precision (Rank 2)",
            "Precision (Rank 3)",
            "Precision (Rank 4)",
            "Precision (Rank 5)",
            "Endurance (Rank 1)",
            "Endurance (Rank 2)",
            "Improved Sprint (Rank 1)",
            "Improved Sprint (Rank 2)",
            "Lightning Reflexes (Rank 1)",
            "Dual Wield Specialization (Rank 1)",
            "Dual Wield Specialization (Rank 2)",
            "Dual Wield Specialization (Rank 3)",
            "Dual Wield Specialization (Rank 4)",
            "Dual Wield Specialization (Rank 5)",
            "Blade Flurry",
            "Sword Specialization (Rank 1)",
            "Sword Specialization (Rank 2)",
            "Sword Specialization (Rank 3)",
            "Sword Specialization (Rank 4)",
            "Sword Specialization (Rank 5)",
            "Weapon Expertise (Rank 1)",
            "Weapon Expertise (Rank 2)",
            "Aggression (Rank 1)",
            "Aggression (Rank 2)",
            "Adrenaline Rush",
            "Agression (Rank 3)",
            "Malice (Rank 1)",
            "Malice (Rank 2)",
            "Malice (Rank 3)",
            "Malice (Rank 4)",
            "Malice (Rank 5)",
            "Ruthlessness (Rank 1)",
            "Ruthlessness (Rank 2)",
            "Ruthlessness (Rank 3)",
            "Improved Slice and Dice (Rank 1)",
            "Improved Slice and Dice (Rank 2)",
            "Relentless Strikes (Rank 1)",
            "Improved Slice and Dice (Rank 3)",
            "Lethality (Rank 1)",
            "Lethality (Rank 2)",
            "Lethality (Rank 3)",
            "Lethality (Rank 4)",
            "Lethality (Rank 5)",
            "Murder (Rank 1)",
            "Murder (Rank 2)"
        }
    },
    ["Priest"] = {
        ["Holy"] = {
            "Wand Specialization (Rank 1)",
            "Wand Specialization (Rank 2)",
            "Wand Specialization (Rank 3)",
            "Wand Specialization (Rank 4)",
            "Wand Specialization (Rank 5)",
            "Spirit Tap (Rank 1)",
            "Spirit Tap (Rank 2)",
            "Spirit Tap (Rank 3)",
            "Spirit Tap (Rank 4)",
            "Spirit Tap (Rank 5)",
            "Healing Focus (Rank 1)",
            "Healing Focus (Rank 2)",
            "Holy Specialization (Rank 1)",
            "Holy Specialization (Rank 2)",
            "Holy Specialization (Rank 3)",
            "Holy Specialization (Rank 4)",
            "Holy Specialization (Rank 5)",
            "Spell Warding (Rank 1)",
            "Divine Fury (Rank 1)",
            "Divine Fury (Rank 2)",
            "Divine Fury (Rank 3)",
            "Divine Fury (Rank 4)",
            "Divine Fury (Rank 5)",
            "Silent Resolve (Rank 1)",
            "Silent Resolve (Rank 2)",
            "Silent Resolve (Rank 3)",
            "Silent Resolve (Rank 4)",
            "Improved Power Word: Fortitude (Rank 1)",
            "Improved Power Word: Fortitude (Rank 2)",
            "Mediation (Rank 1)",
            "Meditation (Rank 2)",
            "Meditation (Rank 3)",
            "Inspiration (Rank 1)",
            "Inspiration (Rank 2)",
            "Inspiration (Rank 3)",
            "Holy Nova (Rank 1)",
            "Improved Healing (Rank 1)",
            "Improved Healing (Rank 2)",
            "Improved Healing (Rank 3)",
            "Inner Focus",
            "Mental Agility (Rank 1)",
            "Mental Agility (Rank 2)",
            "Mental Agility (Rank 3)",
            "Mental Agility (Rank 4)",
            "Mental Agility (Rank 5)",
            "Spritual Guidance (Rank 1)",
            "Spritual Guidance (Rank 2)",
            "Spritual Guidance (Rank 3)",
            "Spritual Guidance (Rank 4)",
            "Spritual Guidance (Rank 5)",
            "Divine Spirit (Rank 1)"
        }
    },
    ["Hunter"] = {
        ["Beast Mastery"] = {
            "Impoved Aspect of the Hawk (Rank 1)",
            "Impoved Aspect of the Hawk (Rank 2)",
            "Impoved Aspect of the Hawk (Rank 3)",
            "Impoved Aspect of the Hawk (Rank 4)",
            "Impoved Aspect of the Hawk (Rank 5)",
            "Improved Revive Pet (Rank 1)",
            "Improved Revive Pet (Rank 2)",
            "Thick Hide (Rank 1)",
            "Thick Hide (Rank 2)",
            "Thick Hide (Rank 3)",
            "Pathfinding (Rank 1)",
            "Pathfinding (Rank 2)",
            "Bestial Swiftness (Rank 1)",
            "Unleashed Fury (Rank 1)",
            "Unleashed Fury (Rank 2)",
            "Unleashed Fury (Rank 3)",
            "Unleashed Fury (Rank 4)",
            "Unleashed Fury (Rank 5)",
            "Ferocity (Rank 1)",
            "Ferocity (Rank 2)",
            "Intimidation",
            "Ferocity (Rank 3)",
            "Ferocity (Rank 4)",
            "Ferocity (Rank 5)",
            "Bestial Discipline (Rank 1)",
            "Frenzy (Rank 1)",
            "Frenzy (Rank 2)",
            "Frenzy (Rank 3)",
            "Frenzy (Rank 4)",
            "Frenzy (Rank 5)",
            "Bestial Wrath",
            "Improved Concussive Shot (Rank 1)",
            "Improved Concussive Shot (Rank 2)",
            "Improved Concussive Shot (Rank 3)",
            "Improved Concussive Shot (Rank 4)",
            "Improved Concussive Shot (Rank 5)",
            "Lethal Shots (Rank 1)",
            "Lethal Shots (Rank 2)",
            "Lethal Shots (Rank 3)",
            "Lethal Shots (Rank 4)",
            "Lethal Shots (Rank 5)",
            "Aimed Shot",
            "Hawk Eye (Rank 1)",
            "Hawk Eye (Rank 2)",
            "Hawk Eye (Rank 3)",
            "Efficiency (Rank 1)",
            "Mortal Shots (Rank 1)",
            "Mortal Shots (Rank 2)",
            "Mortal Shots (Rank 3)",
            "Mortal Shots (Rank 4)",
            "Mortal Shots (Rank 5)"
        }
    }
}
